url : https://rednaw.github.io/

# bootstrap_version: 4.5.3
# jquery_version: 3.6.0
bootstrap_version: 3.4.1
jquery_version: 3.5.1

exclude:
  - Rakefile

# See https://www.zotero.org/styles for more styles
scholar:
   source: .
   style: ./style/archiv-fur-geschichte-der-philosophie.csl
   sort_by: year
   order: descending
   bibliography_list_tag: ul
   repository: ./resources
   bibliography_template: linkitem


